****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZD_071_DYNPRO																																
0302																																
753																																
                40																																
%_HEADER																																
ZD_071_DYNPRO                           0302I0000      0  0192 37  0  0 24 90  0G E                              20230111011555																																
%_DESCRIPTION																																
Details in ewb																																
%_FIELDS																																
HTML_BSP			 87	00	00	00	30	00	  1	  2		  0	  0	  0		 24	U				  1	  1	102									
		CHAR	 20	80	10	08	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
 MODULE STATUS_0110.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0110.																																
