****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZD_071_DYNPRO																																
0200																																
753																																
                40																																
%_HEADER																																
ZD_071_DYNPRO                           0200I0200     18 39192 37  0  0 27122  0G E                              20230111002843																																
%_DESCRIPTION																																
Screen to display connection details																																
%_FIELDS																																
SPFLI-MANDT	2	CHAR	 15	30	00	00	30	00	  3	  3		  0	  0	  0		  0					  0	  0								Client	                                                                                                                                                                                                                                                        X	
SPFLI-MANDT	C	CLNT	  3	A0	00	84	30	08	  3	 21		  0	  0	  0		  0					  6	  0								___	X                                      00	
SPFLI-CARRID	2	CHAR	 16	30	00	04	30	00	  4	  3		  0	  0	  0		  0			CAR		  0	  0								Airline	                                                                                                                                                                                                                                                        X	
SPFLI-CARRID	C	CHAR	  3	A0	00	84	30	08	  4	 21		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
SPFLI-CONNID	2	CHAR	 15	30	00	00	30	00	  5	  3		  0	  0	  0		  0			CON		  0	  0								Flight Number	                                                                                                                                                                                                                                                        X	
SPFLI-CONNID	N	NUMC	  4	A0	00	80	30	00	  5	 21		  0	  0	  0		  0			CON		  8	  0								____	                                       00	
SPFLI-COUNTRYFR	2	CHAR	 12	30	00	04	30	00	  6	  3		  0	  0	  0		  0			LND		  0	  0								Country	                                                                                                                                                                                                                                                        X	
SPFLI-COUNTRYFR	C	CHAR	  3	A0	00	84	00	08	  6	 21		  0	  0	  0		  0			LND		  6	  0								___	X                                      00	
SPFLI-CITYFROM	2	CHAR	 11	30	00	04	30	00	  7	  3		  0	  0	  0		  0					  0	  0								Depart.city	                                                                                                                                                                                                                                                        X	
SPFLI-CITYFROM	C	CHAR	 20	A0	00	84	00	08	  7	 21		  0	  0	  0		  0					 40	  0								____________________	X                                      00	
SPFLI-AIRPFROM	2	CHAR	 15	30	00	04	30	00	  8	  3		  0	  0	  0		  0					  0	  0								Dep. airport	                                                                                                                                                                                                                                                        X	
SPFLI-AIRPFROM	C	CHAR	  3	A0	00	84	00	08	  8	 21		  0	  0	  0		  0					  6	  0								___	X                                      00	
SPFLI-COUNTRYTO	2	CHAR	 12	30	00	04	30	00	  9	  3		  0	  0	  0		  0			LND		  0	  0								Country	                                                                                                                                                                                                                                                        X	
SPFLI-COUNTRYTO	C	CHAR	  3	A0	00	84	00	08	  9	 21		  0	  0	  0		  0			LND		  6	  0								___	X                                      00	
SPFLI-CITYTO	2	CHAR	 17	30	00	04	30	00	 10	  3		  0	  0	  0		  0					  0	  0								Arrival city	                                                                                                                                                                                                                                                        X	
SPFLI-CITYTO	C	CHAR	 20	A0	00	84	00	08	 10	 21		  0	  0	  0		  0					 40	  0								____________________	X                                      00	
SPFLI-AIRPTO	2	CHAR	 15	30	00	04	30	00	 11	  3		  0	  0	  0		  0					  0	  0								Dest. airport	                                                                                                                                                                                                                                                        X	
SPFLI-AIRPTO	C	CHAR	  3	A0	00	84	00	08	 11	 21		  0	  0	  0		  0					  6	  0								___	X                                      00	
SPFLI-FLTIME	2	CHAR	 15	30	00	00	30	00	 12	  3		  0	  0	  0		  0					  0	  0								Flight time	                                                                                                                                                                                                                                                        X	
SPFLI-FLTIME	X	INT4	  6	A0	00	80	00	00	 12	 21		  0	  0	  0		  0				SDURA	 10	  0								______	                                       00	
SPFLI-DEPTIME	2	CHAR	 15	30	00	00	30	00	 13	  3		  0	  0	  0		  0					  0	  0								Departure	                                                                                                                                                                                                                                                        X	
SPFLI-DEPTIME	T	TIME	  8	A0	00	80	00	08	 13	 21		  0	  0	  0		  0					 12	  0								________	X                                      00	
SPFLI-ARRTIME	2	CHAR	 15	30	00	00	30	00	 14	  3		  0	  0	  0		  0					  0	  0								Arrival Time	                                                                                                                                                                                                                                                        X	
SPFLI-ARRTIME	T	TIME	  8	A0	00	80	00	08	 14	 21		  0	  0	  0		  0					 12	  0								________	X                                      00	
SPFLI-DISTANCE	2	CHAR	 10	30	00	00	30	00	 15	  3		  0	  0	  0		  0					  0	  0								Distance	                                                                                                                                                                                                                                                        X	
SPFLI-DISTANCE	P	QUAN	 11	A0	00	80	00	00	 15	 21		  0	  0	  0		  0					  9	  4		SPFLI-DISTID						__.___,____	                                       00	
SPFLI-DISTID	2	CHAR	 13	30	02	00	30	00	 16	  3		  0	  0	  0		  0					  0	  0								Distance in	                                                                                                                                                                                                                                                        X	
SPFLI-DISTID	C	UNIT	  3	A0	02	80	00	08	 16	 21		  0	  0	  0		  0				CUNIT	  6	  0								___	X                                      00	
SPFLI-FLTYPE	C	CHAR	  1	A0	00	81	00	08	 17	  3		  0	  0	  0		  0	C				  2	  0	101							_	X                                      00	
SPFLI-FLTYPE	2	CHAR	  7	30	00	01	30	00	 17	  5		  0	  0	  0		  0	C				  0	  0	101							Charter	                                                                                                                                                                                                                                                        X	
SPFLI-PERIOD	2	CHAR	 15	30	00	00	30	00	 18	  3		  0	  0	  0		  0					  0	  0								n day(s) later	                                                                                                                                                                                                                                                        X	
SPFLI-PERIOD	X	INT1	  3	A0	00	80	00	00	 18	 21		  0	  0	  0		  0					  3	  0								___	                                       00	
		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
MODULE STATUS_0200.																																
																																
PROCESS AFTER INPUT.																																
MODULE USER_COMMAND_0200.																																
