****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZD_071_DYNPRO																																
0303																																
753																																
                40																																
%_HEADER																																
ZD_071_DYNPRO                           0303I0000     18 67192 37  0  0 29107  0G E                              20230111042529																																
%_DESCRIPTION																																
Real time tracking																																
%_FIELDS																																
HTML_TRACKING			107	00	00	00	30	00	  1	  2		  0	  0	  0		 29	U				  1	  1	102									
		CHAR	 20	80	10	08	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
MODULE STATUS_0303.																																
*																																
PROCESS AFTER INPUT.																																
* MODULE USER_COMMAND_0110.																																
