****************************************************************																																
*   This file was generated by Direct Download Enterprise.     *																																
*   Please do not change it manually.                          *																																
****************************************************************																																
%_DYNPRO																																
ZD_071_DYNPRO																																
0100																																
753																																
                40																																
%_HEADER																																
ZD_071_DYNPRO                           0100 0300      8 47192 37  0  0 27121  0G E                              20230111003223																																
%_DESCRIPTION																																
Choose the airline and flight																																
%_FIELDS																																
TXT_INSTRUCTION	0	CHAR	 47	00	00	00	30	00	  3	  2		  0	  0	  0		  0					  0	  0								Please select an airline and a flight number :		
SPFLI-CARRID	2	CHAR	 16	30	00	04	30	00	  5	  2		  0	  0	  0		  0			CAR		  0	  0								Airline	                                                                                                                                                                                                                                                        X	
SPFLI-CARRID	C	CHAR	  3	A0	00	84	00	08	  5	 19		  0	  0	  0		  0			CAR		  6	  0								___	X                                      00	
SPFLI-CONNID	2	CHAR	 15	30	00	00	30	00	  6	  2		  0	  0	  0		  0			CON		  0	  0								Flight Number	                                                                                                                                                                                                                                                        X	
SPFLI-CONNID	N	NUMC	  4	A0	00	80	00	08	  6	 19		  0	  0	  0		  0			CON		  8	  0								____	                                       00	
BTN_SELECT		CHAR	 10	00	00	00	30	00	  8	  2		  0	  0	  0		  0	P				  0	  0	101							Ready & Go	                                                                                                                                                                        SELECT	
OK_CODE		CHAR	 20	80	10	00	00	00	255	  1	O	  0	  0	  0		  0					  0	  0								____________________		
%_FLOWLOGIC																																
PROCESS BEFORE OUTPUT.																																
MODULE STATUS_0100.																																
																																
PROCESS AFTER INPUT.																																
FIELD spfli-connid SELECT * FROM spfli																																
WHERE carrid = spfli-carrid AND connid = spfli-connid.																																
MODULE USER_COMMAND_0100.																																
